# Generated by Django 5.1.1 on 2024-09-12 12:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('department', models.CharField(choices=[('Full-stack developer', 'Full-stack developer'), ('Front-end developer', 'Front-end developer'), ('Back-end developer', 'Back-end developer')], default='Full-stack developer', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='employee_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('category', models.CharField(choices=[('Web design', 'Web design'), ('Graphics design', 'Graphics design'), ('Python', 'Python'), ('Javascript', 'JavaScript'), ('Java', 'Java'), ('Ethical Hacking', 'Ethical Hacking'), ('Database', 'Database'), ('computer basics', 'computer basics')], default='web_design', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
